import os
import smtplib
import feedparser
import urllib.parse
from datetime import datetime, timedelta
from time import mktime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from deep_translator import GoogleTranslator

def fetch_from_google(query):
    """通用的 RSS 抓取逻辑"""
    encoded_query = urllib.parse.quote(query)
    rss_url = f"https://news.google.com/rss/search?q={encoded_query}&hl=en-US&gl=US&ceid=US:en"
    
    feed = feedparser.parse(rss_url)
    items = []
    two_weeks_ago = datetime.now() - timedelta(days=14)

    for entry in feed.entries:
        if not hasattr(entry, 'published_parsed'): 
            continue
        published_time = datetime.fromtimestamp(mktime(entry.published_parsed))
        
        if published_time > two_weeks_ago:
            items.append({
                "title": entry.title,
                "url": entry.link,
                "source": entry.source.get('title', 'Global Media'),
                "date": published_time.strftime('%Y-%m-%d')
            })
        if len(items) >= 20: 
            break
    return items

def get_mtn_intelligence():
    """获取 MTN 动态，具备双重搜索保底机制"""
    subsidaries = [
        'MTN Group', '"MTN South Africa"', '"MTN Nigeria"', 
        '"MTN Ghana"', '"MTN Uganda"', '"MTN Cameroon"', '"MTN Ivory Coast"'
    ]
    query_str = "(" + " OR ".join(subsidaries) + ") when:14d"
    
    print(f"正在尝试高精准搜索: {query_str}")
    news_items = fetch_from_google(query_str)
    
    if not news_items:
        print("⚠️ 高精准搜索未匹配到结果，正在启动保底搜索策略...")
        fallback_query = "MTN Telecom when:14d"
        news_items = fetch_from_google(fallback_query)
        
    return news_items

def send_news_email():
    sender_user = os.environ.get('EMAIL_ADDRESS')
    sender_password = os.environ.get('EMAIL_PASSWORD')
    receiver_user = os.environ.get('RECEIVER_EMAIL')

    news_data = get_mtn_intelligence()
    
    if not news_data:
        news_data = [{
            "title": "System Alert: No major news found in the last 14 days for MTN subsidiaries.",
            "url": "https://news.google.com",
            "source": "System",
            "date": datetime.now().strftime('%Y-%m-%d')
        }]

    translator = GoogleTranslator(source='en', target='zh-CN')
    table_rows = ""
    
    for item in news_data:
        eng_title = item['title']
        try:
            chi_title = translator.translate(eng_title)
        except:
            chi_title = "翻译接口繁忙，请阅读原文"
            
        table_rows += f"""
        <tr>
            <td style="padding: 12px; border: 1px solid #ddd; font-size: 14px;">
                <strong>{eng_title}</strong><br>
                <span style="color: #666; font-size: 11px;">{item['source']} | {item['date']}</span>
            </td>
            <td style="padding: 12px; border: 1px solid #ddd; font-size: 14px; color: #333;">{chi_title}</td>
            <td style="padding: 12px; border: 1px solid #ddd; text-align: center;">
                <a href="{item['url']}" style="display: inline-block; padding: 6px 12px; background-color: #ffcc00; color: #000; text-decoration: none; border-radius: 20px; font-weight: bold; font-size: 12px;">阅读原文</a>
            </td>
        </tr>
        """

    html_content = f"""
    <html>
    <body style="font-family: Arial, sans-serif; padding: 20px; background-color: #f4f4f4;">
        <div style="max-width: 900px; margin: 0 auto; background-color: #fff; border-radius: 8px; overflow: hidden; border: 1px solid #ddd; box-shadow: 0 4px 10px rgba(0,0,0,0.1);">
            <div style="background-color: #ffcc00; padding: 25px; text-align: center;">
                <h1 style="margin: 0; font-size: 24px; color: #000;">MTN Intelligence Report</h1>
                <p style="margin: 5px 0 0; color: #333;">ALEX AI Agent - 全球动态监控</p>
            </div>
            <div style="padding: 20px;">
                <table style="width: 100%; border-collapse: collapse;">
                    <tr style="background-color: #000; color: #fff;">
                        <th style="padding: 12px; text-align: left;">新闻原文 (English)</th>
                        <th style="padding: 12px; text-align: left;">中文导读 (Chinese)</th>
                        <th style="padding: 12px; text-align: center;">链接</th>
                    </tr>
                    {table_rows}
                </table>
            </div>
            <div style="background-color: #f9f9f9; padding: 15px; text-align: center; color: #888; font-size: 12px;">
                Generated by ALEX AI Agent | Current Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
            </div>
        </div>
    </body>
    </html>
    """

    msg = MIMEMultipart()
    msg['Subject'] = f"【MTN 集团情报】{datetime.now().strftime('%m月%d日')} 推送"
    msg['From'] = f"ALEX AI Agent - MTN Intelligence <{sender_user}>"
    msg['To'] = receiver_user
    msg.attach(MIMEText(html_content, 'html'))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(sender_user, sender_password)
            server.send_message(msg)
        print("✅ 任务完成：邮件已发出。")
    except Exception as e:
        print(f"❌ 邮件发送失败: {e}")

if __name__ == "__main__":
    send_news_email()
